---
- name: Upload VIM syntax .RPM
  copy:
    src: '{{ icinga2_upload_vimsyntax_rpm }}'
    dest: '/tmp/{{ icinga2_upload_vimsyntax_rpm }}'

- name: Install VIM syntax RPM
  yum:
    pkg: '/tmp/{{ icinga2_upload_vimsyntax_rpm }}'
    state: installed
