---
- name: Get Icinga2 Apt Key for Debian OS family
  apt_key:
    url: '{{ icinga2_apt_key }}'
    state: present

  #Debian packages require additional packages which are provided by the Debian Monitoring Project repository
- name: Get Debmon Apt Key for Debian OS family (Debian)
  apt_key:
    url: '{{ icinga2_debmon_key }}'
    state: present
  when: ansible_distribution == 'Debian'

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository:
    repo: '{{ item }}'
    update_cache: yes
    state: present
  loop: '{{ icinga2_deb_repos }}'

  #Debian packages require additional packages which are provided by the Debian Monitoring Project repository
- name: Get Debmon Apt Repo for Debian OS family (Debian)
  apt_repository:
    repo: '{{ icinga2_debmon_repo }}'
    update_cache: yes
    state: present
  when: ansible_distribution == 'Debian'

- name: Install Icinga2 packages on Debian OS family
  apt:
    pkg: '{{ item.package }}'
    state: '{{ item.state|default("present") }}'
    update_cache: yes
    install_recommends: no
  loop: '{{ icinga2_core_deb_packages }}'

- name: Install Icinga2 postgres IDO on Debian OS family
  apt:
    name: '{{ item.package }}'
    state: '{{ item.state|default("present") }}'
  loop: '{{ icinga2_ido_postgres_apt_packages }}'
  when: icinga2_ido_with_postgres

- name: Start Icinga2
  service:
    name: icinga2
    state: started
    enabled: yes
