---
- name: Create icingawe2 pg_user
  postgresql_user:
    name: '{{ icingaweb2_pg_user }}'
    password: '{{ icingaweb2_pg_password }}'
    role_attr_flags: NOCREATEDB,NOSUPERUSER
  become_user: postgres
  become: true
  when: icingaweb2_with_postgres

- name: Create icingaweb2 pg_database
  postgresql_db:
    name: '{{ icingaweb2_pg_db }}'
    encoding: 'UTF-8'
    template: 'template0'
    lc_ctype: 'en_US.utf8'
    lc_collate: 'en_US.utf8'
    owner: '{{ icingaweb2_pg_user }}'
  become_user: postgres
  become: true
  when: icingaweb2_with_postgres

- name: Create icingawweb directory
  shell: icingacli setup config directory --group icingaweb2
  args:
    creates: /etc/icingaweb2

- name: Create icingawweb setup token
  shell: icingacli setup token create
  args:
    creates: /etc/icingaweb2/setup.token
