---
- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
      - ../vars

- name: Warn if OS is unsupported
  fail: msg="OS {{ ansible_distribution }} {{ ansible_distribution_major_version }} is unsupported"
  when: not icinga2_supported_os

- name: "Run Debian specific installation"
  include: icinga2_Debian_install.yml
  when: ansible_os_family == 'Debian'

- name: "Run Redhat specific installation"
  include: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- name: "Set up Icinga"
  include: icinga2_configure.yml
  tags: 
   - icinga2_configure

- name: "Set up Icingaweb2"
  include: icingaweb2_configure.yml
  when: icinga2_with_web2
  tags:
   - icinga2_configure

- name: Start Icinga2 after install
  service: name=icinga2 enabled=yes state=running