---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: "molecule-${MOLECULE_DISTRO:-centos7}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    cap_add:
      - SYS_ADMIN
      - SYS_TIME
#  - name: ubuntu1804
#    image: "ubuntu:18.04"
#    env:
#      ADD_GPG: apt
#  - name: ubuntu1604
#    image: "ubuntu:16.04"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml

verifier:
  name: testinfra
  lint:
    name: flake8

scenario:
  name: default
