---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Add gpg on Ubuntu 18.04
      apt:
        name: gpg
        install_recommends: false
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version|int >= 18

  roles:
    - role: VerosK.icinga2
